export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const LOG_OUT = 'LOG_OUT';

export const LOAD_USER_DATA_SUCCESS = 'LOAD_USER_DATA_SUCCESS';

export const FIND_FRIEND_SUCCESS = 'FIND_FRIEND_SUCCESS';
export const FIND_FRIEND_ERROR = 'FIND_FRIEND_ERROR';
export const LOADING_FRIENDS = 'LOADING_FRIENDS';

export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';

export const LOAD_MESSAGE_SUCCESS = 'LOAD_MESSAGE_SUCCESS';
export const LOADING_MESSAGE = 'LOADING_MESSAGE';

export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

export const LOAD_INBOX_SUCCESS = 'LOAD_INBOX_SUCCESS';
export const LOAD_INBOX_FAIL = 'LOAD_INBOX_FAIL'; 
export const LOADING_INBOX = 'LOADING_INBOX'; 
export const UPDATE_INBOX_SUCCESS = 'UPDATE_INBOX_SUCCESS';
export const UPDATE_INBOX_SUCCESS_NEW = 'UPDATE_INBOX_SUCCESS_NEW';

export const SET_READ_STATUS = 'SET_READ_STATUS';
export const UPDATE_SETTING_SUCCESS = 'UPDATE_SETTING_SUCCESS';
export const HIDE_TOAST = 'HIDE_TOAST';

export const INIT_SOCKET = 'INIT_SOCKET';

export const CHANGE_PROFILEPIC_START = 'CHANGE_PROFILEPIC_START';
export const CHANGE_PROFILEPIC_SUCCESS = 'CHANGE_PROFILEPIC_SUCCESS';
export const USER_ONLINE = 'USER_ONLINE';
export const USER_OFFLINE = 'USER_OFFLINE';

export const SET_MESSAGE_STATUS = 'SET_MESSAGE_STATUS';


